
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T08:32:21-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "bee2fdbef078e7c6716d547b747a0e4f8304dbff",
 "version": "0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
