
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T13:32:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d7ab10b0f7bc0833e122a65a4d4bd608ca62fcd",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
