# coding: utf-8

"""
    Developer API - URLR

    API powering the features of URLR.

    The version of the OpenAPI document: 0.3
    Contact: contact@urlr.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from urlr.models.authentification401_response import Authentification401Response

class TestAuthentification401Response(unittest.TestCase):
    """Authentification401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Authentification401Response:
        """Test Authentification401Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Authentification401Response`
        """
        model = Authentification401Response()
        if include_optional:
            return Authentification401Response(
                code = 401,
                message = 'Invalid credentials.'
            )
        else:
            return Authentification401Response(
        )
        """

    def testAuthentification401Response(self):
        """Test Authentification401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
