# coding: utf-8

"""
    Developer API - URLR

    API powering the features of URLR.

    The version of the OpenAPI document: 0.3
    Contact: contact@urlr.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from urlr.models.team200_response import Team200Response

class TestTeam200Response(unittest.TestCase):
    """Team200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Team200Response:
        """Test Team200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Team200Response`
        """
        model = Team200Response()
        if include_optional:
            return Team200Response(
                teams = [
                    urlr.models.team_200_response_teams_inner.team_200_response_teams_inner(
                        id = 131, 
                        name = 'the best team', )
                    ]
            )
        else:
            return Team200Response(
        )
        """

    def testTeam200Response(self):
        """Test Team200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
