# coding: utf-8

"""
    Developer API - URLR

    API powering the features of URLR.

    The version of the OpenAPI document: 0.3
    Contact: contact@urlr.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from urlr.models.folder200_response_folders_inner import Folder200ResponseFoldersInner

class TestFolder200ResponseFoldersInner(unittest.TestCase):
    """Folder200ResponseFoldersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Folder200ResponseFoldersInner:
        """Test Folder200ResponseFoldersInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Folder200ResponseFoldersInner`
        """
        model = Folder200ResponseFoldersInner()
        if include_optional:
            return Folder200ResponseFoldersInner(
                id = 123,
                name = 'folder-campaign-google-ads'
            )
        else:
            return Folder200ResponseFoldersInner(
        )
        """

    def testFolder200ResponseFoldersInner(self):
        """Test Folder200ResponseFoldersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
