# coding: utf-8

"""
    Developer API - URLR

    API powering the features of URLR.

    The version of the OpenAPI document: 0.3
    Contact: contact@urlr.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from urlr.models.reduce_link400_response import ReduceLink400Response

class TestReduceLink400Response(unittest.TestCase):
    """ReduceLink400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReduceLink400Response:
        """Test ReduceLink400Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReduceLink400Response`
        """
        model = ReduceLink400Response()
        if include_optional:
            return ReduceLink400Response(
                code = 401,
                error = -1,
                message = ''
            )
        else:
            return ReduceLink400Response(
        )
        """

    def testReduceLink400Response(self):
        """Test ReduceLink400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
