"""
    Sifflet Backend API

    Requirements: <br>    - [Create your access token through the UI](https://docs.siffletdata.com/docs/generate-an-api-token#create-an-api-token) <br>    - Get your tenant name: if you access to Sifflet with `https://abcdef.siffletdata.com`, then your tenant would be `abcdef`  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from sifflet_sdk.client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from sifflet_sdk.client.exceptions import ApiAttributeError


def lazy_import():
    from sifflet_sdk.client.model.description_dto import DescriptionDto
    from sifflet_sdk.client.model.search_collection_field_level_search_field_dto import SearchCollectionFieldLevelSearchFieldDto
    from sifflet_sdk.client.model.tag_dto import TagDto
    from sifflet_sdk.client.model.user_dto import UserDto
    globals()['DescriptionDto'] = DescriptionDto
    globals()['SearchCollectionFieldLevelSearchFieldDto'] = SearchCollectionFieldLevelSearchFieldDto
    globals()['TagDto'] = TagDto
    globals()['UserDto'] = UserDto


class FieldLevelSearchDto(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('displayed_type',): {
            'SCHEMA': "SCHEMA",
            'DATABASE': "DATABASE",
            'TABLE': "TABLE",
            'EXTERNAL_TABLE': "EXTERNAL_TABLE",
            'VIEW': "VIEW",
            'MATERIALIZED_VIEW': "MATERIALIZED_VIEW",
            'SNOWFLAKE_STREAM': "SNOWFLAKE_STREAM",
            'DASHBOARD': "DASHBOARD",
            'MODEL': "MODEL",
            'DAG': "DAG",
            'ORCHESTRATOR': "ORCHESTRATOR",
            'FIELD': "FIELD",
            'MONITOR': "MONITOR",
            'NONE': "NONE",
            'TRANSFORMATION': "TRANSFORMATION",
            'ML_MODEL': "ML_MODEL",
        },
        ('entity_type',): {
            'DATASOURCE': "DATASOURCE",
            'DATASOURCE_INGESTION_RUN': "DATASOURCE_INGESTION_RUN",
            'DATASET': "DATASET",
            'DASHBOARD': "DASHBOARD",
            'CHART': "CHART",
            'COLLECTION': "COLLECTION",
            'DATASET_FIELD': "DATASET_FIELD",
            'DAG': "DAG",
            'TRANSFORMATION': "TRANSFORMATION",
            'RULE_RUN': "RULE_RUN",
            'INCIDENT': "INCIDENT",
            'USER': "USER",
            'ACCESS_TOKEN': "ACCESS_TOKEN",
            'SIFFLET_RULE': "SIFFLET_RULE",
            'CONFIG': "CONFIG",
            'TAG': "TAG",
            'DOMAIN': "DOMAIN",
            'ALERTING_HOOK': "ALERTING_HOOK",
            'RULE_MONITORING_RECOMMENDATION': "RULE_MONITORING_RECOMMENDATION",
            'DATAPOINT_QUALIFICATION': "DATAPOINT_QUALIFICATION",
            'DECLARED_ASSET': "DECLARED_ASSET",
        },
        ('lineage_platform',): {
            'ATHENA': "ATHENA",
            'BIGQUERY': "BIGQUERY",
            'FIREBOLT': "FIREBOLT",
            'PRESTO': "PRESTO",
            'REDSHIFT': "REDSHIFT",
            'SNOWFLAKE': "SNOWFLAKE",
            'DATABRICKS': "DATABRICKS",
            'HIVE': "HIVE",
            'MSSQL': "MSSQL",
            'MYSQL': "MYSQL",
            'SYNAPSE': "SYNAPSE",
            'POSTGRES': "POSTGRES",
            'H2': "H2",
            'ORACLE': "ORACLE",
            'LIGHTDASH': "LIGHTDASH",
            'LOOKER': "LOOKER",
            'METABASE': "METABASE",
            'TABLEAU': "TABLEAU",
            'POWER_BI': "POWER_BI",
            'QLIK': "QLIK",
            'QUICKSIGHT': "QUICKSIGHT",
            'STITCH': "STITCH",
            'AIRBYTE': "AIRBYTE",
            'AIRFLOW': "AIRFLOW",
            'DAGSTER': "DAGSTER",
            'DBT': "DBT",
            'DBTCLOUD': "DBTCLOUD",
            'FIVETRAN': "FIVETRAN",
            'PREFECT': "PREFECT",
            'TALEND': "TALEND",
            'HUBSPOT': "HUBSPOT",
            'INFORMATICA': "INFORMATICA",
            'MULESOFT': "MULESOFT",
            'SALESFORCE': "SALESFORCE",
            'SEGMENT': "SEGMENT",
            'SLACK': "SLACK",
            'CENSUS': "CENSUS",
            'HIGH_TOUCH': "HIGH_TOUCH",
            'AMAZON_SAGEMAKER': "AMAZON_SAGEMAKER",
            'DATAIKU': "DATAIKU",
            'MICROSOFT_AZURE_ML': "MICROSOFT_AZURE_ML",
            'GOOGLE_ANALYTICS': "GOOGLE_ANALYTICS",
            'SIGMA': "SIGMA",
            'UNKNOWN': "UNKNOWN",
            'AZURE': "AZURE",
            'GOOGLE_DRIVE': "GOOGLE_DRIVE",
            'GOOGLE_SHEETS': "GOOGLE_SHEETS",
            'GOOGLE_CLOUD_STORAGE': "GOOGLE_CLOUD_STORAGE",
            'S3': "S3",
            'HIVE_PROCESS': "HIVE_PROCESS",
            'SPARK_PROCESS': "SPARK_PROCESS",
            'HDFS_STORAGE': "HDFS_STORAGE",
            'EXCEL': "EXCEL",
            'GITHUB': "GITHUB",
        },
        ('health',): {
            'CRITICAL': "CRITICAL",
            'AT_RISK': "AT_RISK",
            'HEALTHY': "HEALTHY",
            'UNMONITORED': "UNMONITORED",
            'NOT_SUPPORTED': "NOT_SUPPORTED",
        },
        ('usage',): {
            'UNSUPPORTED': "UNSUPPORTED",
            'LOW': "LOW",
            'MEDIUM': "MEDIUM",
            'HIGH': "HIGH",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'datasource_name': (str,),  # noqa: E501
            'displayed_type': (str,),  # noqa: E501
            'entity_type': (str,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'label': (str,),  # noqa: E501
            'lineage_platform': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'can_do_auto_coverage': (bool,),  # noqa: E501
            'datasource_id': (str,),  # noqa: E501
            'declared_source': (bool,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'external_descriptions': ([DescriptionDto],),  # noqa: E501
            'fields': (SearchCollectionFieldLevelSearchFieldDto,),  # noqa: E501
            'health': (str,),  # noqa: E501
            'metadata_refresh': (int,),  # noqa: E501
            'owners': ([UserDto],),  # noqa: E501
            'search_weight': (int,),  # noqa: E501
            'tags': ([TagDto],),  # noqa: E501
            'terms': ([TagDto],),  # noqa: E501
            'urn': (str,),  # noqa: E501
            'usage': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'datasource_name': 'datasourceName',  # noqa: E501
        'displayed_type': 'displayedType',  # noqa: E501
        'entity_type': 'entityType',  # noqa: E501
        'id': 'id',  # noqa: E501
        'label': 'label',  # noqa: E501
        'lineage_platform': 'lineagePlatform',  # noqa: E501
        'name': 'name',  # noqa: E501
        'can_do_auto_coverage': 'canDoAutoCoverage',  # noqa: E501
        'datasource_id': 'datasourceId',  # noqa: E501
        'declared_source': 'declaredSource',  # noqa: E501
        'description': 'description',  # noqa: E501
        'external_descriptions': 'externalDescriptions',  # noqa: E501
        'fields': 'fields',  # noqa: E501
        'health': 'health',  # noqa: E501
        'metadata_refresh': 'metadataRefresh',  # noqa: E501
        'owners': 'owners',  # noqa: E501
        'search_weight': 'searchWeight',  # noqa: E501
        'tags': 'tags',  # noqa: E501
        'terms': 'terms',  # noqa: E501
        'urn': 'urn',  # noqa: E501
        'usage': 'usage',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, datasource_name, displayed_type, entity_type, id, label, lineage_platform, name, *args, **kwargs):  # noqa: E501
        """FieldLevelSearchDto - a model defined in OpenAPI

        Args:
            datasource_name (str):
            displayed_type (str):
            entity_type (str):
            id (str):
            label (str):
            lineage_platform (str):
            name (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            can_do_auto_coverage (bool): [optional]  # noqa: E501
            datasource_id (str): [optional]  # noqa: E501
            declared_source (bool): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            external_descriptions ([DescriptionDto]): [optional]  # noqa: E501
            fields (SearchCollectionFieldLevelSearchFieldDto): [optional]  # noqa: E501
            health (str): [optional]  # noqa: E501
            metadata_refresh (int): [optional]  # noqa: E501
            owners ([UserDto]): [optional]  # noqa: E501
            search_weight (int): [optional]  # noqa: E501
            tags ([TagDto]): [optional]  # noqa: E501
            terms ([TagDto]): [optional]  # noqa: E501
            urn (str): [optional]  # noqa: E501
            usage (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.datasource_name = datasource_name
        self.displayed_type = displayed_type
        self.entity_type = entity_type
        self.id = id
        self.label = label
        self.lineage_platform = lineage_platform
        self.name = name
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, datasource_name, displayed_type, entity_type, id, label, lineage_platform, name, *args, **kwargs):  # noqa: E501
        """FieldLevelSearchDto - a model defined in OpenAPI

        Args:
            datasource_name (str):
            displayed_type (str):
            entity_type (str):
            id (str):
            label (str):
            lineage_platform (str):
            name (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            can_do_auto_coverage (bool): [optional]  # noqa: E501
            datasource_id (str): [optional]  # noqa: E501
            declared_source (bool): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            external_descriptions ([DescriptionDto]): [optional]  # noqa: E501
            fields (SearchCollectionFieldLevelSearchFieldDto): [optional]  # noqa: E501
            health (str): [optional]  # noqa: E501
            metadata_refresh (int): [optional]  # noqa: E501
            owners ([UserDto]): [optional]  # noqa: E501
            search_weight (int): [optional]  # noqa: E501
            tags ([TagDto]): [optional]  # noqa: E501
            terms ([TagDto]): [optional]  # noqa: E501
            urn (str): [optional]  # noqa: E501
            usage (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.datasource_name = datasource_name
        self.displayed_type = displayed_type
        self.entity_type = entity_type
        self.id = id
        self.label = label
        self.lineage_platform = lineage_platform
        self.name = name
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
