from typing import Any

from ..complexities import (
    ComplexitiesDict,
    constant,
)


bool_complexities: ComplexitiesDict = {
    '__abs__': constant,
    '__add__': constant,
    '__and__': constant,
    '__bool__': constant,
    '__ceil__': constant,
    '__class__': constant,
    '__delattr__': constant,
    '__dir__': constant,
    '__divmod__': constant,
    '__doc__': constant,
    '__eq__': constant,
    '__float__': constant,
    '__floor__': constant,
    '__floordiv__': constant,
    '__format__': constant,
    '__ge__': constant,
    '__getattribute__': constant,
    '__getnewargs__': constant,
    '__gt__': constant,
    '__hash__': constant,
    '__index__': constant,
    '__init__': constant,
    '__init_subclass__': constant,
    '__int__': constant,
    '__invert__': constant,
    '__le__': constant,
    '__lshift__': constant,
    '__lt__': constant,
    '__mod__': constant,
    '__mul__': constant,
    '__ne__': constant,
    '__neg__': constant,
    '__new__': constant,
    '__or__': constant,
    '__pos__': constant,
    '__pow__': constant,
    '__radd__': constant,
    '__rand__': constant,
    '__rdivmod__': constant,
    '__reduce__': constant,
    '__reduce_ex__': constant,
    '__repr__': constant,
    '__rfloordiv__': constant,
    '__rlshift__': constant,
    '__rmod__': constant,
    '__rmul__': constant,
    '__ror__': constant,
    '__round__': constant,
    '__rpow__': constant,
    '__rrshift__': constant,
    '__rshift__': constant,
    '__rsub__': constant,
    '__rtruediv__': constant,
    '__rxor__': constant,
    '__setattr__': constant,
    '__sizeof__': constant,
    '__str__': constant,
    '__sub__': constant,
    '__subclasshook__': constant,
    '__truediv__': constant,
    '__trunc__': constant,
    '__xor__': constant,
    'as_integer_ratio': constant,
    'bit_count': constant,
    'bit_length': constant,
    'conjugate': constant,
    'denominator': constant,
    'from_bytes': constant,
    'imag': constant,
    'numerator': constant,
    'real': constant,
    'to_bytes': constant,
}
