
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-06T13:53:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "11d062a7a83072d35ccd46bba54aeefc644d09ab",
 "version": "0.4.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
