
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T16:08:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ec61a1bd716af4dd308f27f85c7bd7e6f419b41",
 "version": "2024.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
