
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T10:19:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "768fa90072f4c86ee6aedfd4c5671df1359c87aa",
 "version": "2.35.1rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
