
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T16:17:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8721f84920dac67abdebcfd4c8b7084dc9e45708",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
