from .main import getHTML
from .main import getTitle
from .main import getText
from .main import saveHTML
from .main import getLinks
from .main import getImageUrls
from .main import getElementByClass
from .main import getElementById
from .main import submitForm
from .main import clickButton