
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T13:57:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a673b92125be1f3e43a7ad6ddf06194199ba8a6",
 "version": "0.62.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
