from .handlers import BaseExtraHandler as BaseExtraHandler, ViewHandler as ViewHandler
from _typeshed import Incomplete
from django.contrib import admin

logger: Incomplete
IS_GRAPPELLI_INSTALLED: Incomplete
NOTSET: Incomplete

class ActionFailed(Exception): ...

def confirm_action(modeladmin, request, action, message, success_message: str = '', description: str = '', pk: Incomplete | None = None, extra_context: Incomplete | None = None, title: Incomplete | None = None, template: str = 'admin_extra_buttons/confirm.html', error_message: Incomplete | None = None): ...

class ExtraUrlConfigException(RuntimeError): ...

class DummyAdminform:
    prepopulated_fields: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def __iter__(self): ...

class ExtraButtonsMixin(admin.ModelAdmin):
    change_list_template: str
    change_form_template: str
    extra_button_handlers: Incomplete
    def __init__(self, model, admin_site) -> None: ...
    def message_error_to_user(self, request, exception) -> None: ...
    def check(self, **kwargs): ...
    object: Incomplete
    def get_common_context(self, request, pk: Incomplete | None = None, **kwargs): ...
    def get_extra_urls(self) -> list: ...
    def get_urls(self): ...
    def get_changeform_buttons(self, context): ...
    def get_changelist_buttons(self, context): ...
    def get_action_buttons(self, context): ...
    @property
    def media(self): ...
