from .mixins import ExtraButtonsMixin as ExtraButtonsMixin
from _typeshed import Incomplete
from django.http import HttpResponseRedirect

def handle_basic_auth(request): ...
def get_preserved_filters(request, **extras): ...
def labelize(label): ...
def check_permission(handler, permission, request, obj: Incomplete | None = None): ...

class HttpResponseRedirectToReferrer(HttpResponseRedirect):
    def __init__(self, request, *args, **kwargs) -> None: ...

def get_all_permissions(): ...
def check_decorator_errors(model_admin: ExtraButtonsMixin): ...
