__name__ = "pylapi"
__version__ = "0.12.16"
__description__ = "PyLapi - Python Lightweight API"
__url__ = "https://github.com/jackyko8/pylapi"
__author__ = "Jacky Ko"
__author_email__ = ""
__license__ = "MIT"
__copyright__ = "Copyright Jacky Ko"
