
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-06T16:01:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6f16ada98c525b1d5c285485dc891175053240b",
 "version": "1.0.74"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
