TEST_IMPORT_SETUP_ITEM_IDENTIFIER = 'test_id_01'
TEST_IMPORT_SETUP_ITEM_IDENTIFIER_EDITED = 'test_id_01_edited'
TEST_IMPORT_SETUP_ITEM_NAME = 'test_item'
TEST_IMPORT_SETUP_ITEM_TIME_BUFFER = 100

TEST_IMPORT_SETUP_LABEL = 'test import setup'
TEST_IMPORT_SETUP_LABEL_EDITED = 'test import setup edited'

TEST_IMPORT_SETUP_PROCESS_SIZE = 1

TEST_IMPORTER_BACKEND_PATH = 'importer.tests.importers.TestImporter'
