# Generated by Django 4.0.3 on 2024-04-28 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_emails', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('SEND', 'Send'), ('USND', 'Unsend'), ('PEND', 'Pending'), ('ERRR', 'Error')], default='PEND', max_length=4)),
                ('sendDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='notificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='smsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sendDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='mobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=255)),
                ('recipient_fcmtoken', models.CharField(max_length=255)),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('json_data', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification_images/')),
                ('sendDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.notificationtype')),
            ],
        ),
    ]
