# Generated by Django 4.0.3 on 2024-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='recipient_emails',
            field=models.CharField(max_length=255),
        ),
    ]
