# Generated by Django 4.0.3 on 2024-04-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_emailnotification_recipient_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='status_msg',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
