# Generated by Django 4.0.3 on 2024-04-28 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_emailnotification_status_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='sendDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
