# Generated by Django 4.0.3 on 2024-04-28 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_emailnotification_senddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='sendDate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
