# Generated by Django 4.0.3 on 2024-05-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_emailnotification_senddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenotification',
            name='image',
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='status',
            field=models.CharField(choices=[('SEND', 'Send'), ('USND', 'Unsend'), ('PEND', 'Pending'), ('ERRR', 'Error')], default='PEND', max_length=4),
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='status_msg',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='status',
            field=models.CharField(choices=[('SEND', 'Send'), ('USND', 'Unsend'), ('PEND', 'Pending'), ('ERRR', 'Error')], default='PEND', max_length=4),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='status_msg',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='sendDate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='sendDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
