# Generated by Django 4.0.3 on 2024-05-01 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_remove_mobilenotification_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenotification',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='mobilenotification',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='json_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='sendDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='notificationType',
        ),
    ]
