# Generated by Django 4.0.3 on 2024-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_remove_mobilenotification_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='type',
            field=models.CharField(choices=[('SMS', 'Sms'), ('VFY', 'Verify'), ('ERR', 'Error')], default='SMS', max_length=3),
        ),
    ]
