
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T16:45:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "72b97f86ad59e67a2f5d1f4624293f7d9b97c9e5",
 "version": "2024.5.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
