# Autogenerated by devscripts/update-version.py

__version__ = '2024.05.04.232706'

RELEASE_GIT_HEAD = '96da9525043f78aca4544d01761b13b2140e9ae6'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.05.04.232706dev'
