
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-03T15:13:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2f442dd8eebf5ee7e3308815406efe0eb608c40f",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
