
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-05T18:10:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "10ce340d2eeb7d10ad0fe84d7463bb67adbeaaf4",
 "version": "2024.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
