# Generated by Django 4.2.6 on 2023-10-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cjk404", "0003_alter_pagenotfoundentry_redirect_to_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagenotfoundentry",
            name="url",
            field=models.CharField(max_length=1000, verbose_name="Redirect from URL"),
        ),
    ]
