
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-06T04:23:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "12eb83a59e22ee234d9fd257a704d5ab60c9f2b9",
 "version": "1.25.0.post0.dev84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
