"""
    ELEMENTS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elements_sdk
from elements_sdk.model.custom_field_reference import CustomFieldReference
from elements_sdk.model.volume_mini_reference import VolumeMiniReference
globals()['CustomFieldReference'] = CustomFieldReference
globals()['VolumeMiniReference'] = VolumeMiniReference
from elements_sdk.model.media_root_update import MediaRootUpdate


class TestMediaRootUpdate(unittest.TestCase):
    """MediaRootUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaRootUpdate(self):
        """Test MediaRootUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MediaRootUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
