"""
    ELEMENTS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elements_sdk
from elements_sdk.model.storage_node_mini import StorageNodeMini
globals()['StorageNodeMini'] = StorageNodeMini
from elements_sdk.model.lizard_fs_disk import LizardFSDisk


class TestLizardFSDisk(unittest.TestCase):
    """LizardFSDisk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLizardFSDisk(self):
        """Test LizardFSDisk"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LizardFSDisk()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
