"""
    ELEMENTS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elements_sdk
from elements_sdk.model.elements_group_reference import ElementsGroupReference
from elements_sdk.model.elements_user_reference import ElementsUserReference
from elements_sdk.model.schedule_reference import ScheduleReference
from elements_sdk.model.subtask_reference import SubtaskReference
globals()['ElementsGroupReference'] = ElementsGroupReference
globals()['ElementsUserReference'] = ElementsUserReference
globals()['ScheduleReference'] = ScheduleReference
globals()['SubtaskReference'] = SubtaskReference
from elements_sdk.model.job_update import JobUpdate


class TestJobUpdate(unittest.TestCase):
    """JobUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobUpdate(self):
        """Test JobUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
