# Generated by Django 4.0.7 on 2022-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjk404', '0001_squashed_0006_auto_20211011_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagenotfoundentry',
            name='fallback_redirect',
            field=models.BooleanField(default=False, help_text="This redirect is only matched after all other redirects have failed to match.<br>This allows us to define a general 'catch-all' that is only used as a fallback after more specific redirects have been attempted.", verbose_name='Fallback redirect'),
        ),
    ]
