"""
This file contains the exceptions for the colors module.

Classes:
- ColorError: The base exception for the colors module.
"""


class ColorError(ValueError):...
class ColorTextError(ColorError):...
class ColorBackgroundError(ColorError):...
class ColorStyleError(ColorError):...
class ColorNameError(ColorError):...
