# Generated by Django 1.9.1 on 2016-05-26 11:47
import os

from django.db import (
    migrations,
)

from edulib.core.base.migrations import (
    CorrectSequence,
    LoadFixture,
)


APP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
initial_fixture = os.path.join(APP_DIR, 'fixtures', 'initial_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('lib_udc', '0001_initial'),
    ]

    operations = [
        LoadFixture(initial_fixture),
        CorrectSequence('LibraryUDC'),
    ]
