# Generated by Django 1.9.1 on 2016-05-26 11:44
import os

from django.db import (
    migrations,
)

from edulib.core.base.migrations import (
    ReversibleCorrectSequence,
    ReversibleLoadFixture,
)


APP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
fixture_path = os.path.join(APP_DIR, 'fixtures', 'additional_data.json')


class Migration(migrations.Migration):
    """Внесение дополнительных данных из фикстуры."""

    dependencies = [
        ('lib_example_types', '0003_auto_20180420_0941'),
    ]

    operations = [
        ReversibleLoadFixture(fixture_path),
        ReversibleCorrectSequence('LibraryExampleType'),
    ]
