from _typeshed import Incomplete

register: Incomplete

def default_if_empty(v, default): ...
def get_action_buttons(context, model_admin): ...
def get_changeform_buttons(context, model_admin): ...
def get_changelist_buttons(context, model_admin): ...
