# Generated by Django 4.0.3 on 2024-04-28 07:45

import apps.authsystem.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, default='', max_length=255)),
                ('cellphone', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to=apps.authsystem.models.get_file_loc, validators=[apps.authsystem.models.validate_file])),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='the date this user is created in database')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='the date this user info being updated in database')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
