
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-04T21:21:14-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "32600db1521d4da4619d72aa4a877dd04138751b",
 "version": "2.35.2b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
