
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-04T21:20:58-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "77407c0f5dc56329447c741aca0c97b39ef6a6d7",
 "version": "2.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
