# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mesop/components/table/table.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"mesop/components/table/table.proto\x12\x16mesop.components.table\"7\n\x0fTableClickEvent\x12\x11\n\trow_index\x18\x01 \x01(\x05\x12\x11\n\tcol_index\x18\x02 \x01(\x05\".\n\x08TableRow\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x65ll_values\x18\x02 \x03(\t\"\x86\x01\n\tTableType\x12\x19\n\x11\x64isplayed_columns\x18\x01 \x03(\t\x12\x35\n\x0b\x64\x61ta_source\x18\x02 \x03(\x0b\x32 .mesop.components.table.TableRow\x12\'\n\x1fon_table_click_event_handler_id\x18\x03 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mesop.components.table.table_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TABLECLICKEVENT._serialized_start=62
  _TABLECLICKEVENT._serialized_end=117
  _TABLEROW._serialized_start=119
  _TABLEROW._serialized_end=165
  _TABLETYPE._serialized_start=168
  _TABLETYPE._serialized_end=302
# @@protoc_insertion_point(module_scope)
